version: '3.3'

# 如需配置变量，请在environment中进行变量配置
services:
  api:
    image: linkwechat
    container_name: linkwechat
    environment:
      - JAVA_OPTS=-Xms4096m -Xmx4096m -Duser.timezone=Asia/Shanghai
      - TZ=Asia/Shanghai
      - NACOS_SERVER
      # 如果使用nacos，以下变量可以不进行配置
      - ES_ADDRESS
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASS
      - REDIS_HOST
      - REDIS_PORT
    ports:
      - 8090
    volumes:
      - ./logs:/logs
      # 上传文件地址，请根据实际${ruoyi.profile}自行修改映射
      - ./pic:/app/project/pic
      - ./tmp:/tmp
    restart: always